### ISSUE TITLE
Financial iOS App 竞品分析

### ISSUE THREAD

**Issue by dosthcool** [mooxz/fpd#1]
### Time
2020.3.15-2020.3.31

### Tasks
- [ ] ios app store Apps Collection
- [ ] 分工：自己领任务，建好楼，一个人一层楼，列出App，后期持续维护分析。
- [ ] 上交作业： [石墨链接](https://shimo.im/sheets/KRD6HPpYtQjcDrWG/MODOC/)

### Tools
中国统计网—数据分析 http://www.itongji.cn/cms/article/index 
蝉大师--app排名、关键词分析、ASO优化 https://www.chandashi.com/ 
199IT— 数据报告 http://www.199it.com/ 
艾瑞咨询—数据报告 http://www.iresearch.com.cn/ 
CTR—数据报告 http://www.ctrchina.cn/ 
企鹅智库—数据报告 http://re.qq.com/ 
易观—数据报告、大数据分析平台 https://www.analysys.cn/ 
IT橘子—互联网公司产品数据分析、商业信息服务 https://www.itjuzi.com/ 
Appannie—app市场数据和分析 https://www.appannie.com/cn/insights/ 
众调网—大数据分析和在线调研平台 http://www.91survey.com/ 
google trends — 谷歌关键词趋势排名 https://trends.google.com/trends/ 
mixpanel—移动数据分析平台（外国网站） https://mixpanel.com/retention/ 
comscore—广告分析平台（外国网站） http://www.comscore.com/ 
apps数据分析网站 http://bjx.iimedia.cn/app_rank

**Comment by dosthcool** [comment]
My Task:

- [ ] 鲨鱼记账/pro
- [ ] Pennies
- [ ] 随手记账/Pro
- [ ] 记账城市
- [ ] 闪电记账
- [ ] Qoin
